apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: user-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: user-pod
    spec:
      containers:
        - name: user-container
          image: bollygame94/microserv-assign:users-api
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: secret-appsettings
