apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: user-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: user-pod
    spec:
      containers:
        - name: user-container
          image: bollygame94/microserv-assign:user-api-withoutdb
          ports:
            - containerPort: 80
