apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: user-pod
